
services:
  giornalettiere:
    container_name: giornalettiere
    build:
      context: .
    environment:
      TZ: 'Europe/Rome'
    volumes:
      - ${GIORNALETTIERE_CONFIG}:/app/Settings
      - ${GIORNALETTIERE_DL_CONFIG}:/app/DownloadConfig
      - ${GIORNALETTIERE_DOWNLOAD}:/downloads
    restart: unless-stopped
